Import('env')

asm_files = Glob('*.asm') + ['../bootloader/panic.asm', '../bootloader/ascii.asm', '../bootloader/uart.asm']

c_files = Glob('*.c') + ['../bootloader/panic_c.c', '../bootloader/ascii_c.c']
asm_c_files = env.AssemblyFile(c_files)

library = env.Library('debugging', asm_files + asm_c_files)
Return('library')
