Import('env')

machine_lib = SConscript('./machine/SConscript', exports='env')
bootloader_lib = SConscript('./bootloader/SConscript', exports='env')
kernel_lib = SConscript('./kernel/SConscript', exports='env')
user_echo_lib = SConscript('./user_echo/SConscript', exports='env')

boot = env.Program('bootloader', bootloader_lib + machine_lib)
kernel = env.Program('kernel', kernel_lib + machine_lib)
user_echo = env.Program('user_echo', user_echo_lib + machine_lib)
env.Command('disk.img', [kernel, user_echo], 'python util/concat_img.py $TARGET $SOURCES')
